Repository TeamNobar/Nobar-iOS, pull requests merged in 2022-07, with the labels that each got.

#10 [ADD] Font, ColorSystem, ImageUtil 추가
  Nobar.xcodeproj/project.pbxproj
  Nobar/Resources/Font/Pretendard-Black.otf
  Nobar/Resources/Font/Pretendard-Bold.otf
  Nobar/Resources/Font/Pretendard-ExtraBold.otf
  Nobar/Resources/Font/Pretendard-ExtraLight.otf
  Nobar/Resources/Font/Pretendard-Light.otf
  Nobar/Resources/Font/Pretendard-Medium.otf
  Nobar/Resources/Font/Pretendard-Regular.otf
  Nobar/Resources/Font/Pretendard-SemiBold.otf
  Nobar/Resources/Font/Pretendard-Thin.otf
  Nobar/Resources/plists/Info.plist
  Nobar/Utils/UI/Color.swift
  Nobar/Utils/UI/Font.swift
  Nobar/Utils/UI/ImageFactory.swift
Labels: 🖍 Design, 🍸 승호

#15 [ADD] Color Enum 구조 번경
  Nobar.xcodeproj/project.pbxproj
  Nobar/Resources/Utils/Color.swift
  Nobar/Resources/Utils/Font.swift
  Nobar/Resources/Utils/ImageFactory.swift
  Nobar/Resources/Utils/Theme.swift
Labels: ⚙️ Setting, 🔨 Refactor, 🍸 승호

#17 [ADD] CGFloat Extensions
  Nobar.xcodeproj/project.pbxproj
  Nobar/GlobalExtensions/CGFloat+Extensions.swift
Labels: ⚙️ Setting, 🔨 Refactor, 🍸 승호

#20 [ADD] BaseViewController에 setupConstraint 코드 추가
  Nobar/Scenes/Common/BaseViewController.swift
  Nobar/Scenes/Common/NBTabbarController.swift
  Nobar/Scenes/MyPage/MyPageViewController.swift
Labels: ⚙️ Setting, 🍸 승호

#24 [FEAT] 칵테일 상세 검색 뷰 - 최근 검색어, 추천 검색어 UI 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar/GlobalExtensions/Adjusted+Extension.swift
  Nobar/GlobalExtensions/NSObject+Extension.swift
  Nobar/GlobalExtensions/UICollectionView+Extensions.swift
  Nobar/GlobalExtensions/UITextfield+Extension.swift
  Nobar/Resources/Assets.xcassets/btnBackSearch.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/btnBackSearch.imageset/btnStoreBtnBack.png
  Nobar/Resources/Assets.xcassets/btnBackSearch.imageset/btnStoreBtnBack@2x.png
  Nobar/Resources/Assets.xcassets/btnBackSearch.imageset/btnStoreBtnBack@3x.png
  Nobar/Resources/Assets.xcassets/icnSearch.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/icnSearch.imageset/icnSearch.png
  Nobar/Resources/Assets.xcassets/icnSearch.imageset/icnSearch@2x.png
  Nobar/Resources/Assets.xcassets/icnSearch.imageset/icnSearch@3x.png
  Nobar/Resources/Assets.xcassets/icnUp.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/icnUp.imageset/icnUp.png
  Nobar/Resources/Assets.xcassets/icnUp.imageset/icnUp@2x.png
  Nobar/Resources/Assets.xcassets/icnUp.imageset/icnUp@3x.png
  Nobar/Resources/Assets.xcassets/icnX.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/icnX.imageset/icnX.png
  Nobar/Resources/Assets.xcassets/icnX.imageset/icnX@2x.png
  Nobar/Resources/Assets.xcassets/icnX.imageset/icnX@3x.png
  Nobar/Resources/Utils/ImageFactory.swift
  Nobar/Scenes/Search/Cell/RecentCollectionViewCell.swift
  Nobar/Scenes/Search/Cell/RecommendCollectionViewCell.swift
  Nobar/Scenes/Search/Component/SearchHeaderView.swift
  Nobar/Scenes/Search/Model/SearchModel.swift
  Nobar/Scenes/Search/SearchResultViewController.swift
  Nobar/Scenes/Search/SearchViewController.swift
Labels: 🖍 Design, 🍸 수연, 👀 Feature

#23 [ADD] Networking 로직, 모델 일부, 예시 코드 추가
  Nobar.xcodeproj/project.pbxproj
  Nobar.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Nobar/App/Configuration/Environment.swift
  Nobar/GlobalExtensions/Data+Extensions.swift
  Nobar/Model/BaseRecipe.swift
  Nobar/Model/Glass.swift
  Nobar/Model/Ingredient.swift
  Nobar/Model/Recipe.swift
  Nobar/Model/Skill.swift
  Nobar/Model/TastingNote.swift
  Nobar/Model/TastingTag.swift
  Nobar/Networks/APIRouter/APIRouter.swift
  Nobar/Networks/APIRouter/EndPoint.swift
  Nobar/Networks/Logger/NetworkLogger.swift
  Nobar/Networks/NetworkingService/NetworkingService.swift
  Nobar/Networks/Protocols/Networking.swift
  Nobar/Scenes/MyPage/MyPageViewController.swift
Labels: 📬 API, ⚙️ Setting, 🍸 승호

#27 [FEAT] 칵테일 상세검색 뷰 - 자동완성 UI 및 기능 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar/GlobalExtensions/UILabel+Extension.swift
  Nobar/Scenes/Search/Cell/SearchAutoResultCollectionViewCell.swift
  Nobar/Scenes/Search/Component/SearchHeaderView.swift
  Nobar/Scenes/Search/Component/SearchTextField.swift
  Nobar/Scenes/Search/SearchResultViewController.swift
  Nobar/Scenes/Search/SearchViewController.swift
Labels: 🖍 Design, 🍸 수연, 👀 Feature

#30 [FEATURE] SegmentdControl 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Nobar/Resources/Utils/Color.swift
  Nobar/Scenes/MyPage/MyPageViewController.swift
  Nobar/Utils/UI/NBSegmentedController.swift
Labels: 🖍 Design, 🍸 승호

#28 [FEAT] 홈뷰 레이아웃 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar/GlobalExtensions/UIColor+Extension.swift
  Nobar/Resources/Assets.xcassets/dummy1.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/dummy1.imageset/dummy1.png
  Nobar/Resources/Assets.xcassets/dummy1.imageset/dummy1@2x.png
  Nobar/Resources/Assets.xcassets/dummy1.imageset/dummy1@3x.png
  Nobar/Resources/Assets.xcassets/dummy2.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/dummy2.imageset/dummy2.png
  Nobar/Resources/Assets.xcassets/dummy2.imageset/dummy2@2x.png
  Nobar/Resources/Assets.xcassets/dummy2.imageset/dummy2@3x.png
  Nobar/Resources/Assets.xcassets/icnTag.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/icnTag.imageset/icnTag.png
  Nobar/Resources/Assets.xcassets/icnTag.imageset/icnTag@2x.png
  Nobar/Resources/Assets.xcassets/icnTag.imageset/icnTag@3x.png
  Nobar/Resources/Assets.xcassets/logo.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/logo.imageset/logo.png
  Nobar/Resources/Assets.xcassets/logo.imageset/logo@2x.png
  Nobar/Resources/Assets.xcassets/logo.imageset/logo@3x.png
  Nobar/Resources/Utils/Color.swift
  Nobar/Resources/Utils/ImageFactory.swift
  Nobar/Scenes/Main/Component/CocktailCVC.swift
  Nobar/Scenes/Main/Component/GuideCVC.swift
  Nobar/Scenes/Main/Component/HomeHeaderView.swift
  Nobar/Scenes/Main/Component/RecommendCVC.swift
  Nobar/Scenes/Main/MainViewController.swift
  Nobar/Scenes/Main/Model/CocktailModel.swift
  Nobar/Scenes/Main/Model/GuideModel.swift
  Nobar/Scenes/Main/Model/RecommendModel.swift
Labels: 🖍 Design, 🍸 유진

#34 [FEAT] 상세검색뷰 전체보기 뷰 구현
  Nobar/GlobalExtensions/UIStackView+Extension.swift
  Nobar/Resources/Assets.xcassets/btnCancel.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/btnCancel.imageset/btn_cancel.png
  Nobar/Resources/Assets.xcassets/btnCancel.imageset/btn_cancel@2x.png
  Nobar/Resources/Assets.xcassets/btnCancel.imageset/btn_cancel@3x.png
  Nobar/Resources/Utils/Color.swift
  Nobar/Resources/Utils/Font.swift
  Nobar/Resources/Utils/ImageFactory.swift
  Nobar/Scenes/Search/Cell/RecentCollectionViewCell.swift
  Nobar/Scenes/Search/Cell/SearchTotalResultCollectionViewCell.swift
  Nobar/Scenes/Search/Component/RecipeInfoTagView.swift
  Nobar/Scenes/Search/Component/SearchHeaderView.swift
  Nobar/Scenes/Search/Component/SearchTextField.swift
  Nobar/Scenes/Search/Model/CocktailModel.swift
  Nobar/Scenes/Search/SearchResultViewController.swift
  Nobar/Scenes/Search/SearchTotalResultViewContorller.swift
  Nobar/Scenes/Search/SearchViewController.swift
Labels: 🖍 Design, 🍸 수연, 👀 Feature

#33 [ADD] Fastlane settings
  AppStore_kr.teamnobar.nobar-ios-debug.mobileprovision
  AppStore_kr.teamnobar.nobar-ios-release.mobileprovision
  HM7S6M8AAU.cer
  Nobar.xcodeproj/project.pbxproj
  Nobar.xcworkspace/contents.xcworkspacedata
  Nobar.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Nobar.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  Nobar/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Nobar/Resources/plists/Info.plist
  Podfile
  fastlane/.env
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
Labels: ⚙️ Setting, 🍸 승호

#36 [FEAT] 파일 레퍼런스 추가
  Nobar.xcodeproj/project.pbxproj
  Nobar/Resources/Utils/Color.swift
  Nobar/Scenes/Search/Cell/SearchTotalResultCollectionViewCell.swift
  Nobar/Scenes/Search/Model/CocktailModel.swift
  Nobar/Scenes/Search/Model/SearchCocktailModel.swift
  Nobar/Scenes/Search/SearchTotalResultViewContorller.swift
Labels: 🖍 Design, 🍸 수연, 👀 Feature

#39 [FEAT] 탭바 세개로 정리, 아이콘 임시로 추가
  Nobar/Scenes/Common/TabbarRouter.swift
Labels: 🖍 Design, 🍸 승호

#42 [FEAT] 상세 검색 Flow 변경 및 검색 전체결과 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar/Scenes/Search/Component/SearchHeaderView.swift
  Nobar/Scenes/Search/SearchResultViewController.swift
  Nobar/Scenes/Search/SearchTotalResultViewContorller.swift
  Nobar/Scenes/Search/SearchViewController.swift
Labels: 🖍 Design, 🍸 수연, 👀 Feature

#41 [FEAT] 마이페이지 PageViewController 추가
  Nobar.xcodeproj/project.pbxproj
  Nobar/GlobalExtensions/Array+Extensions.swift
  Nobar/Scenes/Common/BaseView.swift
  Nobar/Scenes/MyPage/MyPageViewController.swift
  Nobar/Scenes/MyPage/PageViewContents/MakeOnLaterRecipesViewController.swift
  Nobar/Scenes/MyPage/PageViewContents/MyPageNavigationView.swift
  Nobar/Scenes/MyPage/PageViewContents/TastingNoteViewController.swift
  Nobar/Utils/UI/NBPageViewController.swift
  Nobar/Utils/UI/NBSegmentedController.swift
Labels: 🍸 승호, 👀 Feature

#43 [CHORE] 상세검색 뷰 코드리뷰 반영
  Nobar/Scenes/Search/SearchResultViewController.swift
  Nobar/Scenes/Search/SearchTotalResultViewContorller.swift
  Nobar/Scenes/Search/SearchViewController.swift
Labels: 🔨 Refactor, 🍸 수연

#45 [FEAT] Color에 알파 옵션 추가
  Nobar/Resources/Utils/Color.swift
Labels: 🖍 Design, 🍸 수연, 👀 Feature

#46 [FEAT] 술로 검색 뷰 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar/Resources/Assets.xcassets/icnFilterDown.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/icnFilterDown.imageset/Group 33757.png
  Nobar/Resources/Assets.xcassets/icnFilterDown.imageset/Group 33757@2x.png
  Nobar/Resources/Assets.xcassets/icnFilterDown.imageset/Group 33757@3x.png
  Nobar/Resources/Utils/ImageFactory.swift
  Nobar/Scenes/Common/TabbarRouter.swift
  Nobar/Scenes/Search/Cell/BaseCocktailCollectionViewCell.swift
  Nobar/Scenes/Search/Cell/RecentCollectionViewCell.swift
  Nobar/Scenes/Search/Cell/SearchTotalResultCollectionViewCell.swift
  Nobar/Scenes/Search/Component/RecipeInfoTagView.swift
  Nobar/Scenes/Search/Component/SearchHeaderView.swift
  Nobar/Scenes/Search/Component/SearchTextField.swift
  Nobar/Scenes/Search/Model/BaseCocktailModel.swift
  Nobar/Scenes/Search/Search.storyboard
  Nobar/Scenes/Search/SearchBaseViewController.swift
  Nobar/Scenes/Search/SearchResultViewController.swift
  Nobar/Scenes/Search/SearchViewController.swift
Labels: 🖍 Design, 🍸 수연, 👀 Feature

#49 [FEAT] 최근 검색 기능 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Nobar/Scenes/Search/Component/SearchHeaderView.swift
  Nobar/Scenes/Search/Model/RecentSearchModel.swift
  Nobar/Scenes/Search/SearchResultViewController.swift
  Nobar/Scenes/Search/SearchViewController.swift
Labels: 🍸 수연, 👀 Feature

#50 [FEAT] 검색뷰 디테일 기능 구현 및 화면전환
  Nobar/Scenes/Search/Component/SearchHeaderView.swift
  Nobar/Scenes/Search/SearchResultViewController.swift
  Nobar/Scenes/Search/SearchViewController.swift
Labels: 🍸 수연, 👀 Feature

#54 [FEAT] 회원가입 UI 및 기능 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar/Resources/Assets.xcassets/icnWarning.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/icnWarning.imageset/XCircle 1.png
  Nobar/Resources/Assets.xcassets/icnWarning.imageset/XCircle 1@2x.png
  Nobar/Resources/Assets.xcassets/icnWarning.imageset/XCircle 1@3x.png
  Nobar/Resources/Utils/ImageFactory.swift
  Nobar/Scenes/SignUp/NicknameViewController.swift
Labels: 🖍 Design, 🍸 수연, 👀 Feature

#55 [FEAT] Custom 팝업 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar/Utils/UI/CustomAlert.swift
Labels: 🖍 Design, 🍸 수연

#66 [FEATURE] add temporary endpoint
  Nobar/App/Configuration/Environment.swift
  Nobar/Model/BaseRecipe.swift
  Nobar/Model/Glass.swift
  Nobar/Model/Recipe.swift
  Nobar/Model/Skill.swift
  Nobar/Model/TastingNote.swift
  Nobar/Networks/Logger/NetworkLogger.swift
  Nobar/Networks/NetworkingService/NetworkingService.swift
Labels: 📬 API, 🍸 승호

#64 [FEAT] 홈뷰 레이아웃 수정
  Nobar/Scenes/Main/Component/HomeHeaderView.swift
  Nobar/Scenes/Main/Component/RecommendCVC.swift
  Nobar/Scenes/Main/MainViewController.swift
  Nobar/Scenes/Main/Model/RecommendModel.swift
Labels: 🖍 Design, 🍸 유진

#63 [FEAT] 스플래시 UI 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar/Resources/Assets.xcassets/splashLogo.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/splashLogo.imageset/splashLogo.png
  Nobar/Resources/Assets.xcassets/splashLogo.imageset/splashLogo@2x.png
  Nobar/Resources/Assets.xcassets/splashLogo.imageset/splashLogo@3x.png
  Nobar/Resources/Lottie/111529-rocket.json
  Nobar/Resources/Utils/ImageFactory.swift
  Nobar/Scenes/Splash/SplashViewController.swift
Labels: 🖍 Design, 🍸 수연

#58 [FEAT] 환경설정 UI 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar/Scenes/Setting/SettingDetailView.swift
  Nobar/Scenes/Setting/SettingHeaderView.swift
  Nobar/Scenes/Setting/SettingViewController.swift
Labels: 🖍 Design, 🍸 수연

#68 [FEAT] 홈뷰 나중에볼 레시피 최대 6개만 보이도록 변경(#61)
  Nobar/Scenes/Main/MainViewController.swift
Labels: 🖍 Design, 🍸 유진

#72 [FEAT] 디테일뷰 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Nobar/Resources/plists/Info.plist
  Nobar/Scenes/Detail/Cell/headerMake/HeaderMakeTableViewCell.swift
  Nobar/Scenes/Detail/Cell/headerMake/HeaderMakeTableViewCell.xib
  Nobar/Scenes/Detail/Cell/headerReady/HeaderReadyTableViewCell.swift
  Nobar/Scenes/Detail/Cell/headerReady/HeaderReadyTableViewCell.xib
  Nobar/Scenes/Detail/Cell/headerRecord/HeaderRecordTableViewCell.swift
  Nobar/Scenes/Detail/Cell/headerRecord/HeaderRecordTableViewCell.xib
  Nobar/Scenes/Detail/Cell/info/InfoTableViewCell.swift
  Nobar/Scenes/Detail/Cell/info/InfoTableViewCell.xib
  Nobar/Scenes/Detail/Cell/ingredients/IngredientsTableViewCell.swift
  Nobar/Scenes/Detail/Cell/ingredients/IngredientsTableViewCell.xib
  Nobar/Scenes/Detail/Cell/ingredients/ingredientItem/IngredientItemCollectionViewCell.swift
  Nobar/Scenes/Detail/Cell/ingredients/ingredientItem/IngredientItemCollectionViewCell.xib
  Nobar/Scenes/Detail/Cell/record/RecordTableViewCell.swift
  Nobar/Scenes/Detail/Cell/record/RecordTableViewCell.xib
  Nobar/Scenes/Detail/Cell/steps/StepsTableViewCell.swift
  Nobar/Scenes/Detail/Cell/steps/StepsTableViewCell.xib
  Nobar/Scenes/Detail/Detail.storyboard
  Nobar/Scenes/Detail/DetailViewController.swift
  Nobar/Scenes/Detail/Model/DetailDataModel.swift
  Nobar/Utils/StoryboardRouter.swift
Labels: 🖍 Design, 🍸 수아

#53 [FEAT] 테이스팅노트 작성뷰 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Nobar/Resources/Assets.xcassets/btnScoreEmpty.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/btnScoreEmpty.imageset/Variant4.png
  Nobar/Resources/Assets.xcassets/btnScoreEmpty.imageset/Variant4@2x.png
  Nobar/Resources/Assets.xcassets/btnScoreEmpty.imageset/Variant4@3x.png
  Nobar/Resources/Assets.xcassets/btnScoreFill.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/btnScoreFill.imageset/Variant4.png
  Nobar/Resources/Assets.xcassets/btnScoreFill.imageset/Variant4@2x.png
  Nobar/Resources/Assets.xcassets/btnScoreFill.imageset/Variant4@3x.png
  Nobar/Resources/Assets.xcassets/btnScoreHalf.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/btnScoreHalf.imageset/Property 1=0.5point.png
  Nobar/Resources/Assets.xcassets/btnScoreHalf.imageset/Property 1=0.5point@2x.png
  Nobar/Resources/Assets.xcassets/btnScoreHalf.imageset/Property 1=0.5point@3x.png
  Nobar/Resources/Assets.xcassets/tagIconGray.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/tagIconGray.imageset/Rectangle 5757.png
  Nobar/Resources/Assets.xcassets/tagIconGray.imageset/Rectangle 5757@2x.png
  Nobar/Resources/Assets.xcassets/tagIconGray.imageset/Rectangle 5757@3x.png
  Nobar/Resources/Assets.xcassets/tagIconPink.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/tagIconPink.imageset/icn_area.png
  Nobar/Resources/Assets.xcassets/tagIconPink.imageset/icn_area@2x.png
  Nobar/Resources/Assets.xcassets/tagIconPink.imageset/icn_area@3x.png
  Nobar/Resources/Utils/ImageFactory.swift
  Nobar/Scenes/Search/Component/SearchTextField.swift
  Nobar/Scenes/WritingNote/Cell/EvaluationCVC.swift
  Nobar/Scenes/WritingNote/Cell/ExperienceCVC.swift
  Nobar/Scenes/WritingNote/Cell/ScoreCVC.swift
  Nobar/Scenes/WritingNote/Cell/SelectCocktailCVC.swift
  Nobar/Scenes/WritingNote/Cell/SelectDateCVC.swift
  Nobar/Scenes/WritingNote/Cell/TasteCVC.swift
  Nobar/Scenes/WritingNote/Cell/TastingNoteHeaderView.swift
  Nobar/Scenes/WritingNote/Component/HeartRatingUISlider.swift
  Nobar/Scenes/WritingNote/Component/TastingNoteTextView.swift
  Nobar/Scenes/WritingNote/Component/TastingTagView.swift
  Nobar/Scenes/WritingNote/WritingNoteViewController.swift
Labels: 🖍 Design, 🍸 유진

#69 [FEAT] 나중에볼 레시피 전체보기 뷰 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar/Scenes/Main/Component/HomeHeaderView.swift
  Nobar/Scenes/Main/LaterRecipeAllViewController.swift
  Nobar/Scenes/Main/MainViewController.swift
Labels: 🖍 Design, 🍸 유진, 👀 Feature

#80 [FEAT] 레시피 상세보기 뷰 디테일 수정
  Nobar/Resources/Assets.xcassets/iconHeart.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/iconHeart.imageset/Variant3.png
  Nobar/Resources/Assets.xcassets/iconHeart.imageset/Variant3@2x.png
  Nobar/Resources/Assets.xcassets/iconHeart.imageset/Variant3@3x.png
  Nobar/Resources/Utils/ImageFactory.swift
  Nobar/Scenes/Detail/Cell/info/InfoTableViewCell.swift
  Nobar/Scenes/Detail/Cell/info/InfoTableViewCell.xib
  Nobar/Scenes/Detail/Cell/ingredients/IngredientsTableViewCell.swift
  Nobar/Scenes/Detail/Cell/ingredients/IngredientsTableViewCell.xib
  Nobar/Scenes/Detail/Cell/ingredients/ingredientItem/IngredientItemCollectionViewCell.swift
  Nobar/Scenes/Detail/Cell/ingredients/ingredientItem/IngredientItemCollectionViewCell.xib
  Nobar/Scenes/Detail/Cell/record/RecordTableViewCell.swift
  Nobar/Scenes/Detail/Cell/record/RecordTableViewCell.xib
  Nobar/Scenes/Detail/Cell/steps/StepsTableViewCell.swift
  Nobar/Scenes/Detail/Detail.storyboard
  Nobar/Scenes/Detail/DetailViewController.swift
  Nobar/Scenes/Detail/Model/DetailDataModel.swift
Labels: 🖍 Design, 🍸 수연

#85 [FEAT] 온보딩 UI 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Nobar/Resources/Assets.xcassets/btn_signup.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/btn_signup.imageset/btn_signup.png
  Nobar/Resources/Assets.xcassets/btn_signup.imageset/btn_signup@2x.png
  Nobar/Resources/Assets.xcassets/btn_signup.imageset/btn_signup@3x.png
  Nobar/Resources/Utils/Font.swift
  Nobar/Resources/Utils/ImageFactory.swift
  Nobar/Scenes/OnBoarding/OnboardingCollectionViewCell.swift
  Nobar/Scenes/OnBoarding/OnboardingPageControl.swift
  Nobar/Scenes/OnBoarding/OnboardingViewController.swift
Labels: 🖍 Design, 🍸 수연, 👀 Feature

#84 [FEAT] 온보딩 플로우 구현, 회원가입 구현
  Nobar.xcodeproj/project.pbxproj
  Nobar.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Nobar/App/RootDelegates/SceneDelegate.swift
  Nobar/Networks/APIRouter/APIRouter.swift
  Nobar/Resources/Lottie/111529-rocket.json
  Nobar/Resources/Lottie/nobar.json
  Nobar/Scenes/SignUp/NicknameViewController.swift
  Nobar/Scenes/Splash/SplashViewController.swift
  Nobar/Utils/NBUtils.swift
  Nobar/Utils/UserDefaultKeys.swift
  Nobar/Utils/UserDefaultStorage.swift
Labels: 🍸 승호, 👀 Feature

#100 [CHORE] 검색뷰 화면전환 버그 해결
  Nobar/Scenes/Search/SearchBaseViewController.swift
Labels: 🐞 BugFix, 🍸 수연

#98 [FEAT] 검색 뷰 API 연결
  Nobar.xcodeproj/project.pbxproj
  Nobar/Model/BaseRecipe.swift
  Nobar/Model/Glass.swift
  Nobar/Model/Ingredient.swift
  Nobar/Model/Recipe.swift
  Nobar/Model/Search.swift
  Nobar/Model/Skill.swift
  Nobar/Networks/APIRouter/APIRouter.swift
  Nobar/Networks/NetworkingService/NetworkingService.swift
  Nobar/Resources/Assets.xcassets/icnSearchText.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/icnSearchText.imageset/icn_search_text.png
  Nobar/Resources/Assets.xcassets/icnSearchText.imageset/icn_search_text@2x.png
  Nobar/Resources/Assets.xcassets/icnSearchText.imageset/icn_search_text@3x.png
  Nobar/Scenes/Search/Cell/BaseCocktailCollectionViewCell.swift
  Nobar/Scenes/Search/Cell/RecommendCollectionViewCell.swift
  Nobar/Scenes/Search/Cell/SearchAutoResultCollectionViewCell.swift
  Nobar/Scenes/Search/Cell/SearchTotalResultCollectionViewCell.swift
  Nobar/Scenes/Search/Component/SearchTextField.swift
  Nobar/Scenes/Search/SearchBaseViewController.swift
  Nobar/Scenes/Search/SearchResultViewController.swift
  Nobar/Scenes/Search/SearchTotalResultViewContorller.swift
  Nobar/Scenes/Search/SearchViewController.swift
Labels: 📬 API, 🍸 수연

#102 [FEAT] 테이스팅노트 작성뷰 세부 기능 구현
  Nobar/Resources/Assets.xcassets/icnDelete.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/icnDelete.imageset/_icn_delete.png
  Nobar/Resources/Assets.xcassets/icnDelete.imageset/_icn_delete@2x.png
  Nobar/Resources/Assets.xcassets/icnDelete.imageset/_icn_delete@3x.png
  Nobar/Resources/Assets.xcassets/icnModify.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/icnModify.imageset/icn_modify.png
  Nobar/Resources/Assets.xcassets/icnModify.imageset/icn_modify@2x.png
  Nobar/Resources/Assets.xcassets/icnModify.imageset/icn_modify@3x.png
  Nobar/Resources/Assets.xcassets/icnTag-1.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/icnTag-1.imageset/icnTag.png
  Nobar/Resources/Assets.xcassets/icnTag-1.imageset/icnTag@2x.png
  Nobar/Resources/Assets.xcassets/icnTag-1.imageset/icnTag@3x.png
  Nobar/Resources/Assets.xcassets/icnUp-1.imageset/icnUp.png
  Nobar/Resources/Assets.xcassets/icnUp-1.imageset/icnUp@2x.png
  Nobar/Resources/Assets.xcassets/icnUp-1.imageset/icnUp@3x.png
  Nobar/Resources/Assets.xcassets/icnWarning-1.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/icnWarning-1.imageset/XCircle 1.png
  Nobar/Resources/Assets.xcassets/icnWarning-1.imageset/XCircle 1@2x.png
  Nobar/Resources/Assets.xcassets/icnWarning-1.imageset/XCircle 1@3x.png
  Nobar/Resources/Assets.xcassets/icnX-1.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/icnX-1.imageset/icnX.png
  Nobar/Resources/Assets.xcassets/icnX-1.imageset/icnX@2x.png
  Nobar/Resources/Assets.xcassets/icnX-1.imageset/icnX@3x.png
  Nobar/Resources/Assets.xcassets/logo-1.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/logo-1.imageset/logo.png
  Nobar/Resources/Assets.xcassets/logo-1.imageset/logo@2x.png
  Nobar/Resources/Assets.xcassets/logo-1.imageset/logo@3x.png
  Nobar/Resources/Assets.xcassets/splashLogo-1.imageset/splashLogo.png
  Nobar/Resources/Assets.xcassets/splashLogo-1.imageset/splashLogo@2x.png
  Nobar/Resources/Assets.xcassets/splashLogo-1.imageset/splashLogo@3x.png
  Nobar/Resources/Utils/ImageFactory.swift
  Nobar/Scenes/WritingNote/Cell/EvaluationCVC.swift
  Nobar/Scenes/WritingNote/Cell/ExperienceCVC.swift
  Nobar/Scenes/WritingNote/Cell/ScoreCVC.swift
  Nobar/Scenes/WritingNote/Cell/SelectDateCVC.swift
  Nobar/Scenes/WritingNote/WritingNoteViewController.swift
Labels: 🖍 Design, 🍸 유진

#107 [FEAT] 홈 뷰 API 연결
  Nobar.xcodeproj/project.pbxproj
  Nobar/Model/Guide.swift
  Nobar/Model/Home.swift
  Nobar/Networks/APIRouter/APIRouter.swift
  Nobar/Scenes/Main/Component/CocktailCVC.swift
  Nobar/Scenes/Main/Component/GuideCVC.swift
  Nobar/Scenes/Main/LaterRecipeAllViewController.swift
  Nobar/Scenes/Main/MainViewController.swift
  Nobar/Scenes/Search/Cell/SearchTotalResultCollectionViewCell.swift
  Nobar/Scenes/Search/Component/SearchTextField.swift
Labels: 📬 API, 🍸 수연

#106 [FEAT] 디테일 페이지 서버통신 구현
  AppStore_kr.teamnobar.nobar-ios-release.mobileprovision
  Nobar.xcodeproj/project.pbxproj
  Nobar/Model/Tag.swift
  Nobar/Networks/APIRouter/APIRouter.swift
  Nobar/Scenes/Common/BaseNavigationController.swift
  Nobar/Scenes/Common/TabbarRouter.swift
  Nobar/Scenes/Detail/Cell/info/InfoTableViewCell.swift
  Nobar/Scenes/Detail/Cell/ingredients/IngredientsTableViewCell.swift
  Nobar/Scenes/Detail/Cell/ingredients/ingredientItem/IngredientItemCollectionViewCell.swift
  Nobar/Scenes/Detail/Cell/steps/StepsTableViewCell.swift
  Nobar/Scenes/Detail/Cell/steps/StepsTableViewCell.xib
  Nobar/Scenes/Detail/DetailViewController.swift
  Nobar/Scenes/Detail/Model/DetailDataModel.swift
  Nobar/Scenes/MyPage/PageViewContents/TastingNotes/TastingNoteViewController.swift
  Nobar/Scenes/MyPage/PageViewContents/TastingNotes/Views/TastingNoteContentView.swift
Labels: 📬 API, 🐞 BugFix, 🍸 승호

#109 [FIX] 술로 검색 오류 해결
  Nobar/Scenes/Search/SearchBaseViewController.swift
Labels: 🐞 BugFix, 🍸 수연

#110 [FEAT] 홈 그래픽 적용
  Nobar/Resources/Assets.xcassets/img_bluehawaii.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/img_bluehawaii.imageset/img_bluehawaii.png
  Nobar/Resources/Assets.xcassets/img_bluehawaii.imageset/img_bluehawaii@2x.png
  Nobar/Resources/Assets.xcassets/img_bluehawaii.imageset/img_bluehawaii@3x.png
  Nobar/Resources/Assets.xcassets/img_cinderella.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/img_cinderella.imageset/img_cinderella.png
  Nobar/Resources/Assets.xcassets/img_cinderella.imageset/img_cinderella@2x.png
  Nobar/Resources/Assets.xcassets/img_cinderella.imageset/img_cinderella@3x.png
  Nobar/Resources/Assets.xcassets/img_mojito.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/img_mojito.imageset/img_mojito.png
  Nobar/Resources/Assets.xcassets/img_mojito.imageset/img_mojito@2x.png
  Nobar/Resources/Assets.xcassets/img_mojito.imageset/img_mojito@3x.png
  Nobar/Resources/Assets.xcassets/img_peachcrush.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/img_peachcrush.imageset/img_peachcrush.png
  Nobar/Resources/Assets.xcassets/img_peachcrush.imageset/img_peachcrush@2x.png
  Nobar/Resources/Assets.xcassets/img_peachcrush.imageset/img_peachcrush@3x.png
  Nobar/Resources/Assets.xcassets/img_sexonthebeach.imageset/Contents.json
  Nobar/Resources/Assets.xcassets/img_sexonthebeach.imageset/img_sexonthebeach.png
  Nobar/Resources/Assets.xcassets/img_sexonthebeach.imageset/img_sexonthebeach@2x.png
  Nobar/Resources/Assets.xcassets/img_sexonthebeach.imageset/img_sexonthebeach@3x.png
  Nobar/Resources/Utils/ImageFactory.swift
  Nobar/Scenes/Main/Component/RecommendCVC.swift
  Nobar/Scenes/Main/Model/RecommendModel.swift
Labels: 🖍 Design, 🍸 수연

#113 [FEAT] 테이스팅 작성뷰 API 연결
  Nobar/Networks/APIRouter/APIRouter.swift
  Nobar/Scenes/MyPage/PageViewContents/TastingNotes/TastingNoteViewController.swift
  Nobar/Scenes/MyPage/PageViewContents/TastingNotes/Views/TastingNoteContentView.swift
  Nobar/Scenes/WritingNote/Cell/EvaluationCVC.swift
  Nobar/Scenes/WritingNote/Cell/ExperienceCVC.swift
  Nobar/Scenes/WritingNote/Cell/ScoreCVC.swift
  Nobar/Scenes/WritingNote/Cell/SelectDateCVC.swift
  Nobar/Scenes/WritingNote/Cell/TasteCVC.swift
  Nobar/Scenes/WritingNote/Component/TastingTagView.swift
  Nobar/Scenes/WritingNote/Model/Status.swift
  Nobar/Scenes/WritingNote/WritingNoteViewController.swift
Labels: 📬 API, 🖍 Design, 🍸 승호

#117 [BUG] 테이스팅 노트 버그 수정
  Nobar.xcodeproj/project.pbxproj
  Nobar.xcodeproj/xcshareddata/xcschemes/Nobar.xcscheme
  Nobar.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  Nobar/Scenes/WritingNote/Cell/TasteCVC.swift
  Nobar/Scenes/WritingNote/Cell/TastingNoteHeaderView.swift
  Nobar/Scenes/WritingNote/CocktailNameSearchViewController.swift
  Nobar/Scenes/WritingNote/WritingNoteViewController.swift
Labels: 🐞 BugFix, 🍸 유진
